Repository instaclustr/operator, pull requests merged in 2023-08, with the labels that each got.

#509 Errors handling were fixed for peerings validation
  apis/clusterresources/v1beta1/azurevnetpeering_types.go
  apis/clusterresources/v1beta1/gcpvpcpeering_types.go
  apis/kafkamanagement/v1beta1/validation.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/samples/clusterresources_v1beta1_azurevnetpeering.yaml
Labels: bug

#507 user graceful creation for redis controller
  controllers/clusters/redis_controller.go
  main.go
Labels: enhancement

#508 Update opensearch doc
  apis/clusters/v1beta1/opensearch_types.go
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  doc/clusters/opensearch.md
Labels: documentation

#511 ResourceStateAnnotation fix for clusterresource and kafkamanagement api groups
  PROJECT
  apis/clusterresources/v1beta1/awsencryptionkey_webhook.go
  apis/clusterresources/v1beta1/awssecuritygroupfirewallrule_webhook.go
  apis/clusterresources/v1beta1/awsvpcpeering_webhook.go
  apis/clusterresources/v1beta1/azurevnetpeering_webhook.go
  apis/clusterresources/v1beta1/cassandrauser_types.go
  apis/clusterresources/v1beta1/clusternetworkfirewallrule_webhook.go
  apis/clusterresources/v1beta1/gcpvpcpeering_webhook.go
  apis/kafkamanagement/v1beta1/kafkaacl_webhook.go
  apis/kafkamanagement/v1beta1/kafkauser_types.go
  apis/kafkamanagement/v1beta1/kafkauser_webhook.go
  apis/kafkamanagement/v1beta1/mirror_webhook.go
  apis/kafkamanagement/v1beta1/topic_webhook.go
  apis/kafkamanagement/v1beta1/webhook_suite_test.go
  config/webhook/manifests.yaml
  main.go
Labels: bug

#518 Added cassandra user creation/deletion integration test
  Makefile
  controllers/clusterresources/cassandrauser_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/datatest/postgresql_v1beta1.yaml
  controllers/tests/cassandra_plus_users_test.go
  controllers/tests/datatest/clusterresources_v1beta1_cassandrauser.yaml
  controllers/tests/datatest/clusters_v1beta1_cassandra.yaml
  controllers/tests/datatest/secret.yaml
  controllers/tests/suite_test.go
  pkg/instaclustr/mock/server/.openapi-generator/FILES
  pkg/instaclustr/mock/server/.openapi-generator/VERSION
  pkg/instaclustr/mock/server/README.md
  pkg/instaclustr/mock/server/api/openapi.yaml
  pkg/instaclustr/mock/server/go/api.go
  pkg/instaclustr/mock/server/go/api_bundle_user.go
  pkg/instaclustr/mock/server/go/api_bundle_user_service.go
  pkg/instaclustr/mock/server/go/model_bundle_user_create_request.go
  pkg/instaclustr/mock/server/go/model_bundle_user_delete_request.go
  pkg/instaclustr/mock/server/go/model_error_message.go
  pkg/instaclustr/mock/server/go/model_generic_response.go
  pkg/instaclustr/mock/server/go/routers.go
  pkg/instaclustr/mock/server/instaclustr_openapi_v2.yaml
  pkg/instaclustr/mock/server/main.go
Labels: test

#525 added Cluster Settings v2 Update for Cassandra
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  controllers/clusters/cassandra_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/config.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/apiv2.go
  pkg/models/errors.go
Labels: enhancement

#533 Fixes for the User CRDs
  apis/clusterresources/v1beta1/redisuser_types.go
  apis/kafkamanagement/v1beta1/kafkauser_types.go
  controllers/clusterresources/cassandrauser_controller.go
  controllers/clusterresources/helpers.go
  controllers/clusterresources/opensearchuser_controller.go
  controllers/clusterresources/redisuser_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/redis_controller.go
  controllers/kafkamanagement/kafkauser_controller.go
  pkg/instaclustr/errors.go
  pkg/models/errors.go
  pkg/models/operator.go
Labels: bug, refactor

#535 integration tests for Cassandra User + Cassandra cluster
  controllers/clusterresources/cassandrauser_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/cassandra_controller_test.go
  controllers/clusters/datatest/cassandra_v1beta1.yaml
  controllers/tests/cassandra_plus_users_test.go
  controllers/tests/datatest/clusters_v1beta1_cassandra.yaml
  controllers/tests/suite_test.go
  pkg/instaclustr/mock/server/go/api_cassandra_cluster_v2_service.go
Labels: test
