Repository instaclustr/operator, pull requests merged in 2023-09, with the labels that each got.

#548 fix externalchanges in cloud provider settings
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/structs.go
Labels: bug

#537 Update Kafka and Cadence resources with PrivateLink
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_kafka.yaml
  pkg/models/kafka_apiv2.go
Labels: enhancement

#554 Exclusion Windows resource was transferred to the APIv2
  PROJECT
  apis/clusterresources/v1beta1/exclusionwindow_types.go
  apis/clusterresources/v1beta1/exclusionwindow_webhook.go
  apis/clusterresources/v1beta1/maintenanceevents_types.go
  apis/clusterresources/v1beta1/maintenanceevents_webhook.go
  apis/clusterresources/v1beta1/webhook_suite_test.go
  apis/clusterresources/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusterresources.instaclustr.com_exclusionwindows.yaml
  config/crd/bases/clusterresources.instaclustr.com_maintenanceevents.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterresources_exclusionwindows.yaml
  config/crd/patches/webhook_in_clusterresources_exclusionwindows.yaml
  config/rbac/clusterresources_exclusionwindow_editor_role.yaml
  config/rbac/clusterresources_exclusionwindow_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/clusterresources_v1beta1_exclusionwindow.yaml
  config/webhook/manifests.yaml
  controllers/clusterresources/exclusionwindow_controller.go
  controllers/clusterresources/maintenanceevents_controller.go
  main.go
  pkg/instaclustr/client.go
  pkg/instaclustr/config.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/errors.go
Labels: refactor

#556 equality fix
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zookeeper_types.go
  controllers/clusters/helpers.go
Labels: refactor

#547 issue-528, handle the user errors
  config/samples/clusters_v1beta1_redis.yaml
  controllers/clusterresources/redisuser_controller.go
  controllers/clusters/redis_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
Labels: refactor

#555 Maintenance Events resource was transfered to the APIv2
  apis/clusterresources/v1beta1/maintenanceevents_types.go
  apis/clusterresources/v1beta1/maintenanceevents_webhook.go
  apis/clusterresources/v1beta1/zz_generated.deepcopy.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusterresources.instaclustr.com_maintenanceevents.yaml
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusterresources_v1beta1_maintenanceevents.yaml
  controllers/clusterresources/maintenanceevents_controller.go
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/config.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/operator.go
Labels: refactor

#562 Cluster's CRDs printing was prettified when kubectl get
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/zookeeper_types.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  pkg/instaclustr/mock/server/go/api_cluster_maintenance_events_v2_service.go
Labels: enhancement

#551 Added Resize Settings and Resize Operations
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_kafka.yaml
  config/samples/clusters_v1beta1_opensearch.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  config/samples/clusters_v1beta1_redis.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/config.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/apiv2.go
  pkg/models/cadence_apiv2.go
  pkg/models/cassandra_apiv2.go
  pkg/models/errors.go
  pkg/models/kafka_apiv2.go
  pkg/models/kafka_connect_apiv2.go
  pkg/models/opensearch_apiv2.go
  pkg/models/postgresql_apiv2.go
  pkg/models/redis_apiv2.go
Labels: enhancement

#565 minor-fixes
  Dockerfile
  config/samples/kafkamanagement_v1beta1_kafkauser.yaml
  controllers/clusters/kafka_controller.go
  controllers/clusters/redis_controller.go
Labels: refactor

#557 get cluster backups, trigger cluster backup and trigger cluster restore were migrated to APIv2
  PROJECT
  apis/clusterresources/v1beta1/clusterbackup_webhook.go
  apis/clusterresources/v1beta1/webhook_suite_test.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/samples/clusterresources_v1beta1_clusterbackup.yaml
  config/samples/clusters_v1beta1_cassandra_restore.yaml
  config/samples/clusters_v1beta1_opensearch_restore.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  config/samples/clusters_v1beta1_postgresql_restore.yaml
  config/samples/clusters_v1beta1_redis_restore.yaml
  config/webhook/manifests.yaml
  controllers/clusterresources/clusterbackup_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  main.go
  pkg/instaclustr/client.go
  pkg/instaclustr/config.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/apiv1.go
  pkg/models/apiv2.go
  pkg/models/errors.go
  pkg/models/operator.go
Labels: refactor

#569 Default helm values to v0.1.2 release were updated
  helm/values.yaml
Labels: enhancement

#566 AWS VPC Peering and Security Group Firewall rule cluster resources enhancement
  controllers/clusterresources/awssecuritygroupfirewallrule_controller.go
  controllers/clusterresources/awsvpcpeering_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/apiv2.go
Labels: bug, enhancement

#571 hot-fix change var for postgres clusterkind
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/samples/clusterresources_v1beta1_clusterbackup.yaml
  controllers/clusterresources/clusterbackup_controller.go
Labels: bug

#570 Fixed bug of the routines deadlock when a job removes itself
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  controllers/clusterresources/awssecuritygroupfirewallrule_controller.go
  controllers/clusterresources/awsvpcpeering_controller.go
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  pkg/scheduler/scheduler.go
Labels: bug

#577 issue-558, PostgreSQL user deletion flow was implemented
  controllers/clusterresources/cassandrauser_controller.go
  controllers/clusterresources/postgresqluser_controller.go
  controllers/clusters/postgresql_controller.go
  pkg/models/operator.go
Labels: enhancement
