Repository instaclustr/operator, pull requests merged in 2023-12, with the labels that each got.

#644 Issue-639, Integration tests for kafkauser controller
  controllers/kafkamanagement/datatest/kafkauser_v1beta1.yaml
  controllers/kafkamanagement/datatest/kafkauser_v1beta1_secret.yaml
  controllers/kafkamanagement/kafkauser_controller.go
  controllers/kafkamanagement/kafkauser_controller_test.go
  pkg/instaclustr/mock/server/go/api_bundle_user.go
  pkg/instaclustr/mock/server/go/api_bundle_user_service.go
Labels: test

#645 Issue-561, Additional columns printers
  apis/clusterresources/v1beta1/awsencryptionkey_types.go
  apis/clusterresources/v1beta1/awsendpointserviceprincipal_types.go
  apis/clusterresources/v1beta1/awssecuritygroupfirewallrule_types.go
  apis/clusterresources/v1beta1/awsvpcpeering_types.go
  apis/clusterresources/v1beta1/azurevnetpeering_types.go
  apis/clusterresources/v1beta1/clusterbackup_types.go
  apis/clusterresources/v1beta1/clusternetworkfirewallrule_types.go
  apis/clusterresources/v1beta1/exclusionwindow_types.go
  apis/clusterresources/v1beta1/gcpvpcpeering_types.go
  apis/clusterresources/v1beta1/opensearchegressrules_types.go
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/zookeeper_types.go
  apis/kafkamanagement/v1beta1/kafkaacl_types.go
  apis/kafkamanagement/v1beta1/mirror_types.go
  apis/kafkamanagement/v1beta1/topic_types.go
  config/crd/bases/clusterresources.instaclustr.com_awsencryptionkeys.yaml
  config/crd/bases/clusterresources.instaclustr.com_awsendpointserviceprincipals.yaml
  config/crd/bases/clusterresources.instaclustr.com_awssecuritygroupfirewallrules.yaml
  config/crd/bases/clusterresources.instaclustr.com_awsvpcpeerings.yaml
  config/crd/bases/clusterresources.instaclustr.com_azurevnetpeerings.yaml
  config/crd/bases/clusterresources.instaclustr.com_clusterbackups.yaml
  config/crd/bases/clusterresources.instaclustr.com_clusternetworkfirewallrules.yaml
  config/crd/bases/clusterresources.instaclustr.com_exclusionwindows.yaml
  config/crd/bases/clusterresources.instaclustr.com_gcpvpcpeerings.yaml
  config/crd/bases/clusterresources.instaclustr.com_opensearchegressrules.yaml
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/crd/bases/kafkamanagement.instaclustr.com_kafkaacls.yaml
  config/crd/bases/kafkamanagement.instaclustr.com_mirrors.yaml
  config/crd/bases/kafkamanagement.instaclustr.com_topics.yaml
Labels: enhancement

#646 Doc for Kafka User Certificates
  doc/usermanagment/user-managment.md
Labels: documentation

#648 redis creation webhook was refactored
  apis/clusters/v1beta1/redis_webhook.go
  config/rbac/role.yaml
  config/samples/clusters_v1beta1_redis.yaml
  pkg/models/errors.go
Labels: enhancement, refactor
