Repository instaclustr/operator, pull requests merged in 2023-07, with the labels that each got.

#475 Adjustments to opensearch spec
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  controllers/clusters/cadence_controller.go
Labels: refactor

#479 Validation for KafkaSpec fields while update was added, redis DC validation was fixed
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/redis_webhook.go
  config/samples/clusterresources_v1beta1_clusterbackup.yaml
  config/samples/clusterresources_v1beta1_maintenanceevents.yaml
  config/samples/clusterresources_v1beta1_nodereload.yaml
  config/samples/clusters_v1beta1_redis.yaml
  controllers/clusterresources/maintenanceevents_controller.go
Labels: bug, enhancement

#483 Added users graceful creation during OpenSearch cluster creation phase
  controllers/clusterresources/opensearchuser_controller.go
  controllers/clusters/opensearch_controller.go
  main.go
  pkg/scheduler/scheduler.go
Labels: enhancement

#481 issue-469, delete all users from deleted cluster
  apis/clusterresources/v1beta1/redisuser_types.go
  config/samples/clusters_v1beta1_redis.yaml
  controllers/clusterresources/redisuser_controller.go
  controllers/clusters/redis_controller.go
Labels: enhancement

#476 Cluster resize on start-up was fixed for all clusters
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/zookeeper_types.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusters_v1beta1_kafka.yaml
  config/samples/clusters_v1beta1_kafkaconnect.yaml
  config/samples/clusters_v1beta1_opensearch.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  config/samples/clusters_v1beta1_redis.yaml
  config/samples/clusters_v1beta1_zookeeper.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/helpers.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/errors.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/instaclustr/mock/server/go/model_apache_zookeeper_data_centre_v2.go
  pkg/models/operator.go
  pkg/models/zookeeper_apiv2.go
Labels: bug

#484 Improve handling of external changes for all clusters
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/zookeeper_types.go
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/helpers.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
  pkg/models/apiv1.go
  pkg/models/apiv2.go
  pkg/models/operator.go
Labels: refactor

#485 credential lifecycle for Kafka
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  apis/kafkamanagement/v1beta1/kafkauser_types.go
  apis/kafkamanagement/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/kafkamanagement.instaclustr.com_kafkausers.yaml
  config/samples/clusters_v1beta1_kafka.yaml
  config/samples/kafkamanagement_v1beta1_kafkauser.yaml
  controllers/clusters/kafka_controller.go
  controllers/kafkamanagement/kafkauser_controller.go
Labels: enhancement

#487 Resource not found error while any cluster deletion is fixed
  config/samples/clusters_v1beta1_cadence.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
Labels: bug

#491 Redis master nodes validation was fixed, PostgreSQL logging was improved
  apis/clusters/v1beta1/redis_types.go
  controllers/clusters/postgresql_controller.go
Labels: bug

#489 Saving default Kafka Connect user credentials
  apis/clusters/v1beta1/kafkaconnect_types.go
  controllers/clusters/kafkaconnect_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
Labels: enhancement

#494 default helm values to v0.1.1 release were updated
  helm/values.yaml
Labels: enhancement

#496 Adjustments to defaulter webhooks of clusters group
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/zookeeper_webhook.go
  config/webhook/manifests.yaml
Labels: bug

#500 User creation job removing bug
  controllers/clusterresources/opensearchuser_controller.go
  controllers/clusters/opensearch_controller.go
Labels: bug

#506 Predicate adjustment for user references
  apis/clusterresources/v1beta1/opensearchuser_webhook.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/redis_controller.go
Labels: refactor

#502 user-detach and graceful user creation were implemented
  config/samples/clusters_v1beta1_kafka.yaml
  controllers/clusters/kafka_controller.go
  controllers/kafkamanagement/kafkauser_controller.go
Labels: enhancement

#501 Added detach functionality for the Cassandra user
  apis/clusterresources/v1beta1/cassandrauser_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  controllers/clusterresources/cassandrauser_controller.go
  controllers/clusters/cassandra_controller.go
Labels: enhancement

#504 Datacenters newly added DataCentres validation
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
Labels: enhancement
