Repository instaclustr/operator, pull requests merged in 2023-10, with the labels that each got.

#575 External Deletion for clusters
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/cassandra_controller_test.go
  controllers/clusters/helpers.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafka_controller_test.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/kafkaconnect_controller_test.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/opensearch_controller_test.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/postgresql_controller_test.go
  controllers/clusters/redis_controller.go
  controllers/clusters/redis_controller_test.go
  controllers/clusters/suite_test.go
  controllers/clusters/zookeeper_controller.go
  controllers/clusters/zookeeper_controller_test.go
  pkg/instaclustr/errors.go
  pkg/instaclustr/mock/server/go/api.go
  pkg/instaclustr/mock/server/go/api_apache_cassandra_provisioning_v2_service.go
  pkg/instaclustr/mock/server/go/api_apache_kafka_connect_provisioning_v2_service.go
  pkg/instaclustr/mock/server/go/api_apache_kafka_provisioning_v2_service.go
  pkg/instaclustr/mock/server/go/api_bundle_user.go
  pkg/instaclustr/mock/server/go/api_bundle_user_service.go
  pkg/instaclustr/mock/server/go/api_open_search_provisioning_v2_service.go
  pkg/models/apiv1.go
  pkg/models/apiv2.go
  pkg/models/operator.go
Labels: enhancement

#583 kafkauser endpoints were migrated to APIv3
  apis/kafkamanagement/v1beta1/kafkauser_types.go
  apis/kafkamanagement/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kafkamanagement.instaclustr.com_kafkausers.yaml
  config/samples/kafkamanagement_v1beta1_kafkauser.yaml
  controllers/kafkamanagement/kafkauser_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/config.go
  pkg/instaclustr/interfaces.go
  pkg/models/kafka_user_apv2.go
Labels: refactor

#582 Handling no external IPs or private cluster for PostgreSQL users is implemented
  controllers/clusterresources/postgresqluser_controller.go
  controllers/clusters/postgresql_controller.go
Labels: enhancement

#587 Instaclustr APIv2 Cluster Settings Update for Redis
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/redis_controller.go
  pkg/models/apiv2.go
  pkg/models/cassandra_apiv2.go
  pkg/models/redis_apiv2.go
Labels: enhancement, refactor

#589 Check for no external IPs or private cluster in PostgreSQL webhook is implemented
  apis/clusters/v1beta1/postgresql_webhook.go
  controllers/clusters/postgresql_controller.go
Labels: enhancement

#595 hotfix: Fixed version of setup-envtest tool until project upgrade
  Makefile
Labels: refactor

#592 issue-591, PostgreSQL user webhook was implemented
  PROJECT
  apis/clusterresources/v1beta1/postgresqluser_webhook.go
  apis/clusterresources/v1beta1/webhook_suite_test.go
  config/webhook/manifests.yaml
  controllers/clusterresources/postgresqluser_controller.go
  controllers/clusters/cassandra_controller.go
  main.go
Labels: enhancement

#593 Cluster settings update for the rest of the clusters
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zookeeper_types.go
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
  pkg/models/cadence_apiv2.go
  pkg/models/cassandra_apiv2.go
  pkg/models/kafka_apiv2.go
  pkg/models/kafka_connect_apiv2.go
  pkg/models/opensearch_apiv2.go
  pkg/models/postgresql_apiv2.go
  pkg/models/redis_apiv2.go
  pkg/models/zookeeper_apiv2.go
Labels: enhancement, refactor

#597 issue-559, Cadence controller integration of the rate limiter
  controllers/clusters/cadence_controller.go
  controllers/clusters/cadence_controller_test.go
  controllers/clusters/datatest/cadence_v1beta1.yaml
  controllers/clusters/datatest/cadence_v1beta1_packaged.yaml
  controllers/clusters/suite_test.go
  pkg/instaclustr/mock/server/go/api.go
  pkg/instaclustr/mock/server/go/api_apache_cassandra_provisioning_v2_service.go
  pkg/instaclustr/mock/server/go/api_apache_kafka_provisioning_v2_service.go
  pkg/instaclustr/mock/server/go/api_cadence_provisioning_v2.go
  pkg/instaclustr/mock/server/go/api_cadence_provisioning_v2_service.go
  pkg/instaclustr/mock/server/go/api_open_search_provisioning_v2_service.go
  pkg/instaclustr/mock/server/go/routers.go
Labels: enhancement, test, refactor

#600 Integration of the rate limiter to the kafka management group
  controllers/clusters/zookeeper_controller.go
  controllers/kafkamanagement/kafkaacl_controller.go
  controllers/kafkamanagement/kafkauser_controller.go
  controllers/kafkamanagement/mirror_controller.go
  controllers/kafkamanagement/topic_controller.go
Labels: enhancement, refactor

#527 issue-522,implementation for OpenSearch Egress Rules lifecycle on APIv2
  PROJECT
  apis/clusterresources/v1beta1/opensearchegressrules_types.go
  apis/clusterresources/v1beta1/opensearchegressrules_webhook.go
  apis/clusterresources/v1beta1/webhook_suite_test.go
  apis/clusterresources/v1beta1/zz_generated.deepcopy.go
  apis/clusters/v1beta1/opensearch_types.go
  config/crd/bases/clusterresources.instaclustr.com_opensearchegressrules.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterresources_opensearchegressrules.yaml
  config/crd/patches/webhook_in_clusterresources_opensearchegressrules.yaml
  config/rbac/clusterresources_opensearchegressrules_editor_role.yaml
  config/rbac/clusterresources_opensearchegressrules_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/clusterresources_v1beta1_opensearchegressrules.yaml
  config/samples/clusters_v1beta1_opensearch.yaml
  config/webhook/manifests.yaml
  controllers/clusterresources/opensearchegressrules_controller.go
  main.go
  pkg/instaclustr/client.go
  pkg/instaclustr/config.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/validation.go
Labels: enhancement

#605 Issue-598, Handling of bundled use only resources updation
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/opensearch_webhook.go
  controllers/clusters/cadence_controller.go
  pkg/models/errors.go
Labels: enhancement

#603 Issue-599, Handle of deleting default secret for KafkaConnect and Zookeeper resources
  controllers/clusters/helpers.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/zookeeper_controller.go
Labels: bug, enhancement
