Repository instaclustr/operator, pull requests merged in 2023-11, with the labels that each got.

#611 Monitoring doc
  doc/monitoring/prometheus.md
Labels: documentation

#608 Two-factor delete enhancement
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
Labels: enhancement

#614 Noderleoad controlelr fix
  controllers/clusterresources/nodereload_controller.go
Labels: bug

#616 Extraction of creation and deletion logic of Cassandra User from controller predicates
  apis/clusterresources/v1beta1/cassandrauser_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/structs_test.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/samples/clusterresources_v1beta1_cassandrauser.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  controllers/clusters/cassandra_controller.go
  controllers/clusters/helpers.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/user.go
  controllers/tests/cassandra_plus_users_test.go
  controllers/tests/helpers.go
  controllers/tests/opensearch_plus_users_test.go
Labels: enhancement

#627 issue-607, KafkaUser crud was moved to Kafka reconciler
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  apis/kafkamanagement/v1beta1/kafkauser_types.go
  controllers/clusters/kafka_controller.go
Labels: refactor

#629 issue-412, documentation refactoring
  config/samples/clusters_v1beta1_cadence.yaml
  controllers/clusters/datatest/cadence_v1beta1.yaml
  controllers/clusters/datatest/cadence_v1beta1_packaged.yaml
  doc/clusterresources/aws-security-group-firewall-rule.md
  doc/clusterresources/azure-vnet-peering.md
  doc/clusterresources/cluster-network-firewall-rule.md
  doc/clusters/cadence.md
  doc/clusters/cassandra.md
  doc/clusters/kafka-connect.md
  doc/clusters/kafka.md
  doc/clusters/opensearch.md
  doc/clusters/postgresql.md
  doc/clusters/redis.md
  doc/clusters/zookeeper.md
  doc/getting-started.md
  doc/kafkamanagment/kafka-acl.md
  doc/usermanagment/user-managment.md
Labels: documentation
