Repository instaclustr/operator, pull requests merged in 2024-01, with the labels that each got.

#653 Issue-635 ApiExtensions package
  apis/clusterresources/v1beta1/cassandrauser_types.go
  apis/clusterresources/v1beta1/opensearchuser_types.go
  apis/clusterresources/v1beta1/postgresqluser_types.go
  apis/clusterresources/v1beta1/redisuser_types.go
  apis/clusterresources/v1beta1/structs.go
  apis/clusterresources/v1beta1/zz_generated.deepcopy.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  apis/kafkamanagement/v1beta1/kafkauser_types.go
  apis/kafkamanagement/v1beta1/usercertificate_types.go
  apis/kafkamanagement/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusterresources.instaclustr.com_cassandrausers.yaml
  config/crd/bases/clusterresources.instaclustr.com_opensearchusers.yaml
  config/crd/bases/clusterresources.instaclustr.com_postgresqlusers.yaml
  config/crd/bases/clusterresources.instaclustr.com_redisusers.yaml
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/kafkamanagement.instaclustr.com_kafkausers.yaml
  controllers/kafkamanagement/usercertificate_controller.go
  controllers/tests/cassandra_plus_users_test.go
  controllers/tests/opensearch_plus_users_test.go
  pkg/apiextensions/references.go
  pkg/apiextensions/zz_generated.deepcopy.go
Labels: refactor

#663 PostgreSQL validation webhook fix
  apis/clusters/v1beta1/postgresql_types.go
Labels: bug

#657 External changes messages enhancement
  controllers/clusterresources/cassandrauser_controller.go
  controllers/clusterresources/opensearchuser_controller.go
  controllers/clusterresources/postgresqluser_controller.go
  controllers/clusterresources/redisuser_controller.go
  controllers/clusters/helpers.go
  controllers/kafkamanagement/usercertificate_controller.go
  pkg/models/operator.go
  pkg/utils/dcomparison/map_diff.go
  pkg/utils/dcomparison/map_diff_test.go
  pkg/utils/user_creds_from_secret.go
Labels: enhancement

#664 Extensions feature for the PostgreSQL custom reosurce
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  doc/clusters/postgresql.md
  pkg/apiextensions/zz_generated.deepcopy.go
  pkg/models/postgresql_apiv2.go
Labels: enhancement

#667 Default helm values were updated to v0.1.4 release
  helm/values.yaml
Labels: enhancement

#671 Validation webhooks codebase enhancement
  apis/clusterresources/v1beta1/azurevnetpeering_types.go
  apis/clusterresources/v1beta1/azurevnetpeering_webhook.go
  apis/clusterresources/v1beta1/exclusionwindow_types.go
  apis/clusterresources/v1beta1/exclusionwindow_webhook.go
  apis/clusterresources/v1beta1/gcpvpcpeering_types.go
  apis/clusterresources/v1beta1/gcpvpcpeering_webhook.go
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/redis_webhook.go
Labels: enhancement

#670 Issue-669, Immutable DC name for Redis
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_webhook.go
  pkg/models/errors.go
Labels: bug, enhancement

#672 Issue-654, Prohibiting cluster spec updating until they are running
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/zookeeper_webhook.go
  pkg/models/errors.go
Labels: enhancement

#680 External changes on several failed updates
  controllers/clusters/cassandra_controller.go
  controllers/clusters/helpers.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/suite_test.go
  controllers/clusters/zookeeper_controller.go
  main.go
  pkg/ratelimiter/rate_limiter.go
Labels: refactor

#678 on premises automation has been removed by default
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/rbac/role.yaml
  config/samples/onpremises/clusters_v1beta1_cadence.yaml
  config/samples/onpremises/clusters_v1beta1_cassandra.yaml
  config/samples/onpremises/clusters_v1beta1_kafka.yaml
  config/samples/onpremises/clusters_v1beta1_kafkaconnect.yaml
  config/samples/onpremises/clusters_v1beta1_postgresql.yaml
  config/samples/onpremises/clusters_v1beta1_redis.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  pkg/models/errors.go
  pkg/models/on_premises.go
Labels: enhancement

#688 Default helm values were updated to v0.1.5 release
  helm/values.yaml
Labels: enhancement

#677 Redis replicationFactor/replicaNodes immutable
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/structs.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/helpers.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/kafkaconnect_controller_test.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
  pkg/models/operator.go
Labels: enhancement

#689 External changes on several failed updates for all clusters
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/zookeeper_types.go
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/helpers.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/suite_test.go
  controllers/clusters/zookeeper_controller.go
  controllers/tests/suite_test.go
  main.go
  pkg/models/operator.go
Labels: enhancement, refactor

#682 Opensearch status update
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/generic_status.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  config/samples/clusters_v1beta1_opensearch.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/datatest/cadence_v1beta1_packaged.yaml
  controllers/clusters/datatest/opensearch_v1beta1.yaml
  controllers/clusters/helpers.go
  controllers/clusters/opensearch_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/instaclustr/mock/server/go/api_open_search_provisioning_v2.go
  pkg/models/apiv2_generic.go
  pkg/models/errors.go
  pkg/models/opensearch_apiv2.go
Labels: enhancement, refactor
