Repository instaclustr/operator, pull requests merged in 2024-02, with the labels that each got.

#693 pre-commit hook was added, .env and creds-secret were removed
  .gitignore
  .pre-commit-config.yaml
  .secrets.baseline
  Makefile
  README.md
  config/manager/kustomization.yaml.tmpl
  scripts/make_creds_secret.sh
  scripts/secret.yaml
Labels: enhancement

#695 readme-update
  README.md
Labels: documentation

#692 Generics refactor
  apis/clusters/v1beta1/generic_spec.go
  apis/clusters/v1beta1/generic_status.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusters_v1beta1_opensearch.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/opensearch_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/apiv2.go
  pkg/models/apiv2_generic.go
Labels: refactor

#694 tags immutability
  .secrets.baseline
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/zookeeper_types.go
  apis/clusters/v1beta1/zookeeper_webhook.go
  config/samples/clusters_v1beta1_postgresql.yaml
  config/samples/clusters_v1beta1_redis.yaml
  config/samples/clusters_v1beta1_zookeeper.yaml
Labels: enhancement

#697 Cassandra codebase refactor
  .secrets.baseline
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/generic_spec.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_opensearch.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/opensearch_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/cassandra_apiv2.go
  pkg/utils/slices/slices.go
  pkg/utils/slices/slices_test.go
Labels: refactor

#699 Check for operator version and basic image update logic were implemented
  .secrets.baseline
  apis/clusters/v1beta1/postgresql_types.go
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/clusters/cadence_controller.go
  main.go
  pkg/models/operator.go
  pkg/models/upgrade_check.go
  pkg/scheduler/scheduler.go
  pkg/upgradecheck/upgrade_check.go
Labels: enhancement

#701 Kafka codebase refactor
  .secrets.baseline
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/kafka_webhook_test.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/samples/clusters_v1beta1_kafka.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/datatest/kafka_v1beta1.yaml
  controllers/clusters/helpers.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/opensearch_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/cassandra_apiv2.go
  pkg/models/kafka_apiv2.go
Labels: refactor

#704 Service Monitor for Prometheus metrics scraping was added
  config/default/kustomization.yaml
Labels: enhancement

#703 Redis codebase refactor
  .secrets.baseline
  apis/clusters/v1beta1/generic_spec.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/samples/clusters_v1beta1_redis.yaml
  controllers/clusters/redis_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/redis_apiv2.go
Labels: refactor

#691 tests for opensearch webhook were implemented
  apis/clusters/v1beta1/kafka_webhook_test.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/opensearch_webhook_test.go
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/webhook_suite_test.go
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  controllers/clusters/datatest/kafka_v1beta1.yaml
  controllers/clusters/datatest/opensearch_v1beta1.yaml
  pkg/instaclustr/mock/appversionsmock/models.go
  pkg/models/errors.go
Labels: test, refactor

#708 on-premises provisioning for phase 1 was implemented
  .secrets.baseline
  Makefile
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/kafka_webhook_test.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/default/kustomization.yaml
  config/rbac/role.yaml
  config/samples/onpremises/clusters_v1beta1_cadence.yaml
  config/samples/onpremises/clusters_v1beta1_cassandra.yaml
  config/samples/onpremises/clusters_v1beta1_kafka.yaml
  config/samples/onpremises/clusters_v1beta1_kafkaconnect.yaml
  config/samples/onpremises/clusters_v1beta1_postgresql.yaml
  config/samples/onpremises/clusters_v1beta1_redis.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/on_premises.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  pkg/models/errors.go
  pkg/models/validation.go
Labels: enhancement

#710 issue-698, Save default user ref for zookeeper
  .secrets.baseline
  apis/clusters/v1beta1/zookeeper_types.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  controllers/clusters/zookeeper_controller.go
Labels: enhancement

#707 validation for required fields was implemented
  .secrets.baseline
  Makefile
  PROJECT
  apis/clusterresources/v1beta1/awsencryptionkey_webhook.go
  apis/clusterresources/v1beta1/awsendpointserviceprincipal_webhook.go
  apis/clusterresources/v1beta1/awssecuritygroupfirewallrule_webhook.go
  apis/clusterresources/v1beta1/awsvpcpeering_webhook.go
  apis/clusterresources/v1beta1/azurevnetpeering_webhook.go
  apis/clusterresources/v1beta1/cassandrauser_webhook.go
  apis/clusterresources/v1beta1/clusterbackup_webhook.go
  apis/clusterresources/v1beta1/clusternetworkfirewallrule_webhook.go
  apis/clusterresources/v1beta1/exclusionwindow_webhook.go
  apis/clusterresources/v1beta1/gcpvpcpeering_webhook.go
  apis/clusterresources/v1beta1/maintenanceevents_webhook.go
  apis/clusterresources/v1beta1/nodereload_webhook.go
  apis/clusterresources/v1beta1/opensearchegressrules_webhook.go
  apis/clusterresources/v1beta1/opensearchuser_webhook.go
  apis/clusterresources/v1beta1/redisuser_webhook.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/zookeeper_webhook.go
  apis/kafkamanagement/v1beta1/kafkaacl_webhook.go
  apis/kafkamanagement/v1beta1/kafkauser_webhook.go
  apis/kafkamanagement/v1beta1/mirror_webhook.go
  apis/kafkamanagement/v1beta1/topic_webhook.go
  apis/kafkamanagement/v1beta1/usercertificate_webhook.go
  config/samples/clusterresources_v1beta1_awsendpointserviceprincipal.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  config/webhook/manifests.yaml
  pkg/utils/dcomparison/map_diff_test.go
  pkg/utils/requiredfieldsvalidator/validator.go
  pkg/utils/requiredfieldsvalidator/validator_test.go
  pkg/utils/user_creds_from_secret_test.go
Labels: enhancement, test

#712 issue-698, Save default user ref for kafkaconnect
  .secrets.baseline
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  controllers/clusters/kafkaconnect_controller.go
Labels: enhancement

#715 Cluster Sync Event
  .secrets.baseline
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/validation.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/redis_controller.go
  pkg/models/operator.go
Labels: enhancement, refactor

#713 clusters general validation was covered with tests
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/validation_test.go
Labels: enhancement, test

#716 kafkamanagement general validation was covered with tests
  apis/kafkamanagement/v1beta1/validation.go
  apis/kafkamanagement/v1beta1/validation_test.go
Labels: enhancement, test

#709 KafkaConnect code base refactor
  .secrets.baseline
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/cassandra_webhook.go
  apis/clusters/v1beta1/generic_spec.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafka_webhook.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/kafkaconnect_types_test.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/opensearch_webhook.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/redis_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_kafka.yaml
  config/samples/clusters_v1beta1_kafkaconnect.yaml
  controllers/clusterresources/helpers.go
  controllers/clusters/cadence_controller.go
  controllers/clusters/datatest/kafkaconnect_v1beta1.yaml
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/kafkaconnect_controller_test.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/apiv2_generic.go
  pkg/models/cassandra_apiv2.go
  pkg/models/kafka_apiv2.go
  pkg/models/kafka_connect_apiv2.go
  pkg/models/opensearch_apiv2.go
  pkg/models/redis_apiv2.go
Labels: refactor

#719 Generic cluster spec tests fix
  apis/clusters/v1beta1/validation_test.go
Labels: test

#721 Cadence codebase refactor
  .secrets.baseline
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/generic_spec.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  controllers/clusters/cadence_controller.go
  controllers/clusters/datatest/cadence_v1beta1.yaml
  controllers/clusters/datatest/cadence_v1beta1_packaged.yaml
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/apiv2.go
  pkg/models/cadence_apiv2.go
  pkg/models/errors.go
Labels: refactor

#723 `dcomprasion` StructsDiff was implemented
  .secrets.baseline
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/zookeeper_types.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  controllers/clusters/cassandra_controller.go
  controllers/clusters/helpers.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
  pkg/utils/dcomparison/map_diff.go
  pkg/utils/dcomparison/struct_diff.go
  pkg/utils/dcomparison/struct_diff_test.go
Labels: enhancement

#724 PostgreSQL CR codebase refeactor
  .secrets.baseline
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  controllers/clusters/datatest/postgresql_v1beta1.yaml
  controllers/clusters/postgresql_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/postgresql_apiv2.go
Labels: enhancement

#725 total nodes number displaying for clusters was implemented
  .secrets.baseline
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/generic_status.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/opensearch_types.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/zookeeper_types.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_cassandras.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_kafkas.yaml
  config/crd/bases/clusters.instaclustr.com_opensearches.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_redis.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
Labels: enhancement

#727 Zookeeper CR codebase refactor
  .secrets.baseline
  apis/clusters/v1beta1/cadence_types.go
  apis/clusters/v1beta1/cadence_webhook.go
  apis/clusters/v1beta1/cassandra_types.go
  apis/clusters/v1beta1/kafka_types.go
  apis/clusters/v1beta1/kafkaconnect_types.go
  apis/clusters/v1beta1/kafkaconnect_webhook.go
  apis/clusters/v1beta1/postgresql_types.go
  apis/clusters/v1beta1/postgresql_webhook.go
  apis/clusters/v1beta1/redis_types.go
  apis/clusters/v1beta1/structs.go
  apis/clusters/v1beta1/validation.go
  apis/clusters/v1beta1/validation_test.go
  apis/clusters/v1beta1/zookeeper_types.go
  apis/clusters/v1beta1/zookeeper_webhook.go
  apis/clusters/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/clusters.instaclustr.com_cadences.yaml
  config/crd/bases/clusters.instaclustr.com_kafkaconnects.yaml
  config/crd/bases/clusters.instaclustr.com_postgresqls.yaml
  config/crd/bases/clusters.instaclustr.com_zookeepers.yaml
  config/samples/clusters_v1beta1_cadence.yaml
  config/samples/clusters_v1beta1_cassandra.yaml
  config/samples/clusters_v1beta1_kafkaconnect.yaml
  config/samples/clusters_v1beta1_postgresql.yaml
  config/samples/clusters_v1beta1_zookeeper.yaml
  controllers/clusterresources/awsencryptionkey_controller.go
  controllers/clusterresources/awsendpointserviceprincipal_controller.go
  controllers/clusterresources/awssecuritygroupfirewallrule_controller.go
  controllers/clusterresources/awsvpcpeering_controller.go
  controllers/clusterresources/azurevnetpeering_controller.go
  controllers/clusterresources/clusternetworkfirewallrule_controller.go
  controllers/clusterresources/gcpvpcpeering_controller.go
  controllers/clusters/cadence_controller.go
  controllers/clusters/cassandra_controller.go
  controllers/clusters/datatest/cadence_v1beta1.yaml
  controllers/clusters/datatest/cadence_v1beta1_packaged.yaml
  controllers/clusters/datatest/kafkaconnect_v1beta1.yaml
  controllers/clusters/datatest/postgresql_v1beta1.yaml
  controllers/clusters/datatest/zookeeper_v1beta1.yaml
  controllers/clusters/helpers.go
  controllers/clusters/kafka_controller.go
  controllers/clusters/kafkaconnect_controller.go
  controllers/clusters/kafkaconnect_controller_test.go
  controllers/clusters/on_premises.go
  controllers/clusters/opensearch_controller.go
  controllers/clusters/postgresql_controller.go
  controllers/clusters/redis_controller.go
  controllers/clusters/zookeeper_controller.go
  controllers/kafkamanagement/mirror_controller.go
  pkg/instaclustr/client.go
  pkg/instaclustr/interfaces.go
  pkg/instaclustr/mock/client.go
  pkg/models/redis_apiv2.go
  pkg/models/zookeeper_apiv2.go
  pkg/scheduler/scheduler.go
Labels: refactor
